// AUTO-GENERATED by scripts/generate-types.sh — do not edit by hand.
// Source of truth: ts-rs derives in crates/review-core and src-tauri.


export type AddCommentArgs = { file: string, side: DiffSide, start_line: number, end_line: number, body: string, comment_type: CommentType, severity: Severity, context_before: string, context_content: string, context_after: string, };

export type AddEditArgs = { file: string, start_line: number, end_line: number, old_content: string, new_content: string, description: string, associated_comment_id: string | null, };

export type Comment = { id: string, type: CommentType, file: string, line_range: LineRange, body: string, severity: Severity, resolved: boolean, created_at: string, context: CommentContext, };

export type CommentContext = { before: string, content: string, after: string, };

export type CommentType = "comment" | "suggestion" | "issue" | "auto_edit";

/**
 * A single commit in the repository, with DAG layout info.
 */
export type CommitInfo = { oid: string, short_oid: string, parent_oids: Array<string>, author_name: string, author_email: string, timestamp: number, summary: string, branches: Array<string>, tags: Array<string>, is_head: boolean, 
/**
 * DAG lane index (column) for this commit.
 */
lane: number, 
/**
 * DAG edges from this commit to its parents.
 */
edges: Array<DagEdge>, 
/**
 * Number of active lanes at this row (for SVG width).
 */
lane_count: number, };

/**
 * A range of commits (plus optionally working tree) to diff.
 */
export type CommitRange = { 
/**
 * The selected commit OIDs, in topological order (oldest first).
 */
commits: Array<string>, 
/**
 * Whether to include the working tree in the diff.
 */
include_working_tree: boolean, };

export type ConnectionProfile = { id: string, name: string, ssh_host: string, repo_path: string, };

/**
 * An edge in the DAG graph connecting a commit to its parent.
 */
export type DagEdge = { 
/**
 * Lane of this commit (source).
 */
from_lane: number, 
/**
 * Lane of the parent commit (target).
 */
to_lane: number, 
/**
 * Color index for this edge.
 */
color: number, };

/**
 * A single file that was changed in a diff.
 */
export type DiffFile = { path: string, status: FileStatus, old_path: string | null, additions: number, deletions: number, };

export type DiffSide = "old" | "new";

export type Edit = { id: string, file: string, line_range: EditLineRange, old_content: string, new_content: string, description: string, applied_at: string, associated_comment_id: string | null, };

export type EditLineRange = { start: number, end: number, };

/**
 * Full file contents for the diff viewer (old side + new side).
 */
export type FileDiffContent = { path: string, old_content: string, new_content: string, status: FileStatus, };

export type FileStatus = "Added" | "Deleted" | "Modified" | "Renamed" | "Copied";

export type LineRange = { side: DiffSide, start: number, end: number, };

/**
 * The result of computing a merged diff over a commit range.
 */
export type MergedDiff = { files: Array<DiffFile>, base_oid: string | null, head_description: string, };

/**
 * Result of opening a repo.
 */
export type RepoInfo = { workdir: string, current_branch: string | null, };

export type ReviewSession = { version: string, session: SessionMeta, comments: Array<Comment>, edits: Array<Edit>, summary: string | null, };

export type SessionMeta = { id: string, repo: string, review_location: string, branch: string | null, base_commit: string | null, head_commit: string, reviewed_commits: Array<string>, created_at: string, updated_at: string, };

export type Severity = "info" | "warning" | "error" | "suggestion";
