#!/usr/bin/env bash
# Generate src/api/generatedTypes.ts from ts-rs derives in the workspace.
#
# Runs `cargo test --features ts-export` for each crate that has TS-derived
# types, then concatenates every per-type .ts file into a single module.
# The concat-into-one approach avoids the relative-import path mismatch
# that arises when ts-rs is used across crates at different manifest
# depths (review-core vs src-tauri).
#
# Run manually after changing any IPC DTO. The pre-commit hook
# (scripts/check.sh fast) verifies the output is up-to-date via
# `git diff --exit-code`.

set -euo pipefail

cd "$(dirname "$0")/.."

BINDINGS_DIR="bindings"
OUT_FILE="src/api/generatedTypes.ts"

rm -rf "$BINDINGS_DIR"

cargo test --features ts-export -p review-core --quiet >/dev/null
cargo test --features ts-export -p readcode --quiet >/dev/null

if [ ! -d "$BINDINGS_DIR" ]; then
  echo "Error: $BINDINGS_DIR was not created. Did the ts-rs derives run?" >&2
  exit 1
fi

{
  echo "// AUTO-GENERATED by scripts/generate-types.sh — do not edit by hand."
  echo "// Source of truth: ts-rs derives in crates/review-core and src-tauri."
  echo ""
  for f in "$BINDINGS_DIR"/*.ts; do
    grep -v -E '^(import |// This file was generated by)' "$f"
  done
} > "$OUT_FILE"

rm -rf "$BINDINGS_DIR"
